-- a) Basic

-- Find the total revenue generated overall.
WITH JOINED AS (
SELECT 
	P.PRODUCT_ID,
    SUM(P.PRICE * O.QUANTITY) AS TOTAL_REVENUE_PER_PRODUCT
FROM
	PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY P.PRODUCT_ID)
SELECT 
	SUM(TOTAL_REVENUE_PER_PRODUCT) AS REVENUE_OVERALL FROM JOINED;
    
-- Find the maximum order quantity in a single order.
SELECT 
	MAX(QUANTITY) AS MAX_ORDER_QUANTITY
FROM 
	ORDERS; -- YOU DID NOT SPECIFY WHICH COLUMNS TO TAKE.
-- Find the minimum product price.
SELECT 
	MIN(PRICE) AS MIN_PRICE
FROM 
	PRODUCTS;
-- b) Medium

-- Find the total revenue generated by each user.
SELECT
    U.NAME AS USER_NAME,
    SUM(P.PRICE * O.QUANTITY) AS revenue_per_prod
FROM
	USERS U LEFT JOIN ORDERS O 
    ON U.USER_ID = O.USER_ID
    JOIN PRODUCTS P ON 
    P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY U.NAME;
-- Find the average order value per user
-- (order value = quantity × price).
SELECT
    U.NAME AS USER_NAME,
    ROUND(AVG(P.PRICE * O.QUANTITY),2) AS AVG_ORD_VAL
FROM
	USERS U LEFT JOIN ORDERS O 
    ON U.USER_ID = O.USER_ID
    JOIN PRODUCTS P ON 
    P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY U.NAME;

-- Find the total revenue generated per day.

-- Find the number of distinct products ordered by each user.
-- Find the user who has ordered the highest total quantity.
-- Find the category with the highest total revenue.
-- Find the total number of orders for each category.

-- c) HARD – FAANG LEVELLED

-- Find users whose total spending is greater than the average spending of all users.
-- Find the product that generated the highest revenue.
-- Find users who ordered at least one product from every category.