-- a) Basic

-- 1. Find all orders with the user name and order date for every order placed.
SELECT 
    U.USER_NAME AS USR_NAME,
    O.ORDER_DATE AS ORD_DATE
FROM 
	USERS U JOIN ORDERS O ON
    U.USER_ID = O.USER_ID;
    
-- 2. Find all products along with their seller name and seller rating.
SELECT 
	S.SELLER_NAME,
    S.RATING,
    P.PRODUCT_ID,
    P.PRODUCT_NAME
FROM
	SELLERS S JOIN PRODUCTS P ON
    S.SELLER_ID = P.SELLER_ID;
-- 3. Find all completed orders with the user name, product name, and quantity for each order item.
SELECT 
	U.USER_NAME AS USR_NAME,
    P.PRODUCT_NAME AS PRD_NAME,
    OI.QUANTITY
FROM 
	PRODUCTS P JOIN ORDER_ITEMS OI ON
	P.PRODUCT_ID = OI.PRODUCT_ID JOIN
    ORDERS O ON 
    O.ORDER_ID = OI.ORDER_ID JOIN USERS U ON
    U.USER_ID = O.USER_ID AND O.ORDER_STATUS = LOWER('COMPLETED');
	
-- b) Medium
-- 4. Find each user and the total number of orders they placed, including users who placed no orders.
SELECT 
	O.USER_ID AS USR_ID,
    COUNT(O.ORDER_ID) AS TOTAL_NUMBER_OF_ORDS
FROM 
	USERS U LEFT JOIN ORDERS O ON
    U.USER_ID = O.USER_ID
    GROUP BY U.USER_ID;
	
-- 5. Find each seller and the total number of distinct products they sell.
	SELECT
		S.SELLER_ID,
        COUNT(DISTINCT P.PRODUCT_ID) AS PRODS
	FROM 
		SELLERS S JOIN PRODUCTS P ON
        S.SELLER_ID = P.SELLER_ID
        GROUP BY S.SELLER_ID;
-- 6. Find the total revenue generated by each product category from completed orders only.
	SELECT 
		P.CATEGORY AS PRD_CATEGORY,
		SUM(P.PRICE * OI.QUANTITY) AS REVENUE
	FROM 
		PRODUCTS P JOIN ORDER_ITEMS OI
        ON P.PRODUCT_ID = OI.PRODUCT_ID 
        JOIN ORDERS O ON O.ORDER_ID = OI.ORDER_ID
        AND O.ORDER_STATUS = 'completed'
        GROUP BY P.CATEGORY;
-- 7. Find all users who have placed at least one order containing a product in the Books category.
	SELECT 
		DISTINCT U.USER_ID,
        U.USER_NAME
	FROM 
		USERS U JOIN ORDERS O ON
        U.USER_ID = O.USER_ID JOIN
		ORDER_ITEMS OI ON 
		O.ORDER_ID = OI.ORDER_ID JOIN PRODUCTS P ON
        P.PRODUCT_ID = OI.PRODUCT_ID 
	WHERE P.CATEGORY IN ('Books');
		
-- 8. Find the total amount spent by each user on completed orders only.
SELECT
	U.USER_ID,
    SUM(P.PRICE * OI.QUANTITY) AS AMT_SPENT
FROM
	USERS U 
    JOIN ORDERS O ON
		U.USER_ID = O.USER_ID
    JOIN ORDER_ITEMS OI ON
		O.ORDER_ID = OI.ORDER_ID
	JOIN PRODUCTS P ON
		P.PRODUCT_ID = OI.PRODUCT_ID
	WHERE O.ORDER_STATUS = 'completed'
    GROUP BY U.USER_ID;
-- 9. Find the sellers whose products were ordered by users from at least two different cities, considering completed orders only.
	SELECT
		S.SELLER_ID,
        COUNT(DISTINCT U.CITY) AS CT
	FROM 
		SELLERS S 
        JOIN PRODUCTS P ON
			S.SELLER_ID = P.SELLER_ID
		JOIN ORDER_ITEMS OI ON
			OI.PRODUCT_ID = P.PRODUCT_ID
		JOIN ORDERS O ON
			O.ORDER_ID = OI.ORDER_ID
		JOIN USERS U ON
			U.USER_ID = O.USER_ID
	WHERE
		O.ORDER_STATUS = 'completed'
        GROUP BY S.SELLER_ID
        HAVING COUNT(DISTINCT U.CITY) >1;
			
-- c) HARD - FAANG LEVELLED
-- 10. Find the user who has purchased from the highest number of distinct sellers, considering completed orders only.
SELECT 
	U.USER_ID,
    COUNT(DISTINCT P.SELLER_ID) AS DIST_PRD_CT
FROM
	USERS U 
    JOIN ORDERS O ON
		U.USER_ID = O.USER_ID
	JOIN ORDER_ITEMS OI ON
		O.ORDER_ID = OI.ORDER_ID
	JOIN PRODUCTS P ON
		P.PRODUCT_ID = OI.PRODUCT_ID
WHERE
	O.ORDER_STATUS = 'completed'
	GROUP BY U.USER_ID
    ORDER BY DIST_PRD_CT DESC
    LIMIT 1;
