-- a) Basic
-- Count how many users performed each event (view_product, add_to_cart, purchase).
WITH COLM AS (
SELECT
	USER_ID,
    MIN(CASE WHEN EVENT_NAME = 'view_product' THEN 1  END) AS VP,
    MIN(CASE WHEN EVENT_NAME = 'add_to_cart' THEN 1  END) AS AC,
    MIN(CASE WHEN EVENT_NAME = 'purchase' THEN 1  END) AS P
FROM
	EVENTS
    GROUP BY USER_ID)
SELECT 
	COUNT(VP) AS CT1,
    COUNT(AC) AS CT2,
    COUNT(P) AS CT3
FROM 
	COLM ;
-- Count how many users performed at least one purchase.          
WITH CT AS (        
SELECT 
	USER_ID,
    SUM(CASE WHEN EVENT_NAME = LOWER('VIEW_PRODUCT') THEN 1 ELSE 0 END) AS VP_CT,
    SUM(CASE WHEN EVENT_NAME = LOWER('ADD_TO_CART') THEN 1 ELSE 0 END) AS AC_CT,
    SUM(CASE WHEN EVENT_NAME = LOWER('PURCHASE') THEN 1 ELSE 0 END) AS P_CT
FROM
	EVENTS
    GROUP BY USER_ID)
SELECT 
	*
FROM CT WHERE P_CT >=1;


-- b) Medium
-- Count how many users moved from view_product → add_to_cart in the correct order.
WITH MIN_TIME AS(
SELECT
	USER_ID,
    MIN(EVENT_TIME) AS MIN_EVT_TM_VWP
FROM
	EVENTS
    WHERE EVENT_NAME = LOWER('VIEW_PRODUCT')
	GROUP BY USER_ID
)
SELECT
	COUNT(DISTINCT M.USER_ID) AS CT_OF_CORRECT_ORDERS
FROM
	MIN_TIME M  
    JOIN EVENTS E ON
		M.USER_ID = E.USER_ID
        AND E.EVENT_NAME = LOWER('ADD_TO_CART')
	WHERE E.EVENT_TIME > MIN_EVT_TM_VWP;


-- Count how many users moved from add_to_cart → purchase in the correct order.
WITH MIN_TIME AS(
SELECT
	USER_ID,
    MIN(EVENT_TIME) AS MIN_EVT_TM_VWP
FROM
	EVENTS
    WHERE EVENT_NAME = LOWER('ADD_TO_CART')
	GROUP BY USER_ID
)
SELECT
	COUNT(DISTINCT M.USER_ID) AS CT_OF_CORRECT_ORDERS
FROM
	MIN_TIME M  
    JOIN EVENTS E ON
		M.USER_ID = E.USER_ID
        AND E.EVENT_NAME = LOWER('PURCHASE')
	WHERE E.EVENT_TIME > MIN_EVT_TM_VWP;

-- 5. Count how many users completed the full funnel:
-- view_product → add_to_cart → purchase in order.
WITH VP_STEP AS (
SELECT
	USER_ID,
    MIN(EVENT_TIME) AS MIN_TIME_VP
FROM
	EVENTS 
    WHERE EVENT_NAME = LOWER('VIEW_PRODUCT')
    GROUP BY USER_ID),
    AC_STEP AS (
SELECT
	VS.USER_ID,
    MIN(E.EVENT_TIME) AS MIN_TIME_AC
FROM 
	VP_STEP VS
    JOIN EVENTS E ON
		VS.USER_ID = E.USER_ID AND
        EVENT_NAME = LOWER('ADD_TO_CART') AND
        E.EVENT_TIME > MIN_TIME_VP 
	GROUP BY
    VS.USER_ID),
    
    P_STEP AS (
SELECT 
	AC.USER_ID,
    MIN(EV.EVENT_TIME) AS MIN_TIME_P
FROM 
	AC_STEP AC
    JOIN EVENTS EV ON
		AC.USER_ID=EV.USER_ID AND
        EV.EVENT_TIME > MIN_TIME_AC AND 
        EV.EVENT_NAME = LOWER('PURCHASE')
	GROUP BY 
    AC.USER_ID)
SELECT 
	COUNT(DISTINCT USER_ID)  AS FINAL_CT
FROM 
	P_STEP;


WITH VP_STEP AS (
SELECT
	USER_ID,
    MIN(EVENT_TIME) AS MIN_TIME_VP
FROM
	EVENTS 
WHERE EVENT_NAME = LOWER('VIEW_PRODUCT')
GROUP BY USER_ID
),
AC_STEP AS (
SELECT
	VS.USER_ID,
    MIN(E.EVENT_TIME) AS MIN_TIME_AC
FROM 
	VP_STEP VS
    JOIN EVENTS E ON
		VS.USER_ID = E.USER_ID
        AND E.EVENT_NAME = LOWER('ADD_TO_CART')
        AND E.EVENT_TIME > MIN_TIME_VP 
GROUP BY VS.USER_ID
),
P_STEP AS (
SELECT 
	AC.USER_ID,
    MIN(EV.EVENT_TIME) AS MIN_TIME_P
FROM 
	AC_STEP AC
    JOIN EVENTS EV ON
		AC.USER_ID = EV.USER_ID
        AND EV.EVENT_TIME > MIN_TIME_AC 
        AND EV.EVENT_NAME = LOWER('PURCHASE')
GROUP BY AC.USER_ID
)
SELECT 
	(SELECT COUNT(*) FROM VP_STEP) AS STEP1_USERS,
    (SELECT COUNT(*) FROM AC_STEP) AS STEP2_USERS,
    (SELECT COUNT(*) FROM P_STEP) AS STEP3_USERS;



-- 7. Calculate conversion rate from:
-- view_product → add_to_cart
-- add_to_cart → purchase
WITH VP_STEP AS (
SELECT
	USER_ID,
    MIN(EVENT_TIME) AS MIN_TIME_VP
FROM
	EVENTS 
WHERE EVENT_NAME = LOWER('VIEW_PRODUCT')
GROUP BY USER_ID
),
AC_STEP AS (
SELECT
	VS.USER_ID,
    MIN(E.EVENT_TIME) AS MIN_TIME_AC
FROM 
	VP_STEP VS
    JOIN EVENTS E ON
		VS.USER_ID = E.USER_ID
        AND E.EVENT_NAME = LOWER('ADD_TO_CART')
        AND E.EVENT_TIME > MIN_TIME_VP 
GROUP BY VS.USER_ID
),
P_STEP AS (
SELECT 
	AC.USER_ID,
    MIN(EV.EVENT_TIME) AS MIN_TIME_P
FROM 
	AC_STEP AC
    JOIN EVENTS EV ON
		AC.USER_ID = EV.USER_ID
        AND EV.EVENT_TIME > MIN_TIME_AC 
        AND EV.EVENT_NAME = LOWER('PURCHASE')
GROUP BY AC.USER_ID
),
COUNTS AS (
SELECT 
	(SELECT COUNT(*) FROM VP_STEP) AS STEP1_USERS,
    (SELECT COUNT(*) FROM AC_STEP) AS STEP2_USERS,
    (SELECT COUNT(*) FROM P_STEP) AS STEP3_USERS
)
SELECT
	STEP1_USERS,
    STEP2_USERS,
    STEP3_USERS,
    ROUND(100.0 * STEP2_USERS / STEP1_USERS, 2) AS VIEW_TO_CART_PCT,
    ROUND(100.0 * STEP3_USERS / STEP2_USERS, 2) AS CART_TO_PURCHASE_PCT,
    ROUND(100.0 * STEP3_USERS / STEP1_USERS, 2) AS FULL_FUNNEL_PCT
FROM COUNTS;




-- 8.Count how many users completed the full funnel within 30 minutes of their first view_product.
WITH VP_TABLE AS (
SELECT 
	USER_ID,
    MIN(EVENT_TIME) AS MIN_VP
FROM
	EVENTS
WHERE EVENT_NAME = 'view_product'
GROUP BY USER_ID
),
AC_TABLE AS (
SELECT
	VP.USER_ID,
    VP.MIN_VP,
    MIN(E.EVENT_TIME) AS MIN_AC
FROM
	VP_TABLE VP 
	JOIN EVENTS E ON
		VP.USER_ID = E.USER_ID
		AND E.EVENT_NAME = 'add_to_cart'
		AND E.EVENT_TIME > VP.MIN_VP
GROUP BY VP.USER_ID, VP.MIN_VP
),
P_TABLE AS (
SELECT
	AC.USER_ID,
    AC.MIN_VP,
    AC.MIN_AC,
    MIN(EV.EVENT_TIME) AS MIN_P
FROM
	AC_TABLE AC 
	JOIN EVENTS EV ON
		AC.USER_ID = EV.USER_ID
		AND EV.EVENT_NAME = 'purchase'
		AND EV.EVENT_TIME > AC.MIN_AC
GROUP BY AC.USER_ID, AC.MIN_VP, AC.MIN_AC
)
SELECT 
	COUNT(*) AS FULL_FUNNEL_WITHIN_30_MIN
FROM P_TABLE
WHERE TIMESTAMPDIFF(MINUTE, MIN_VP, MIN_P) <= 30;
-- Count how many users completed the funnel where each step 
-- happens within 15 minutes of the previous step.


-- For each signup date, calculate:
-- number of users who viewed product
-- number who added to cart after viewing
-- number who purchased after adding